services:
  - type: web
    name: mirror-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
